// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoWNPfS_R5Sf9-x6KwTZuuqSVVjhNPH3w',
    appId: '1:350911462798:web:f77ddff5585ff9804eb8df',
    messagingSenderId: '350911462798',
    projectId: 'drive-doctor-315ad',
    authDomain: 'drive-doctor-315ad.firebaseapp.com',
    storageBucket: 'drive-doctor-315ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR-uZz_hmainhqTHmy23lFtBm_Lxyg6gM',
    appId: '1:350911462798:android:6431902a557b303d4eb8df',
    messagingSenderId: '350911462798',
    projectId: 'drive-doctor-315ad',
    storageBucket: 'drive-doctor-315ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd1Z98wH7jo-fz454-YpWtiXfxg5LkUpM',
    appId: '1:350911462798:ios:9de5a4f292518b484eb8df',
    messagingSenderId: '350911462798',
    projectId: 'drive-doctor-315ad',
    storageBucket: 'drive-doctor-315ad.firebasestorage.app',
    iosBundleId: 'com.example.doctorDrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd1Z98wH7jo-fz454-YpWtiXfxg5LkUpM',
    appId: '1:350911462798:ios:9de5a4f292518b484eb8df',
    messagingSenderId: '350911462798',
    projectId: 'drive-doctor-315ad',
    storageBucket: 'drive-doctor-315ad.firebasestorage.app',
    iosBundleId: 'com.example.doctorDrive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoWNPfS_R5Sf9-x6KwTZuuqSVVjhNPH3w',
    appId: '1:350911462798:web:f569c53db531d3744eb8df',
    messagingSenderId: '350911462798',
    projectId: 'drive-doctor-315ad',
    authDomain: 'drive-doctor-315ad.firebaseapp.com',
    storageBucket: 'drive-doctor-315ad.firebasestorage.app',
  );
}
